version: "3.9"
services:
  db:
    # ここにpathを入れることもできる。
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306

    # DB mySQLに関しての設定が入っている。
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # # コンテナtoコンテナ
      # - db-store:/var/lib/mysql
      # # pathの書き方。（②の概念での書き方）コンテナtoローカル
      # - ./docker/db/logs:/var/log/mysql
      # # DBの設定ファイル
      # - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      # MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      # - MYSQL_DATABASE=${DB_NAME}
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASS}
      # - MYSQL_ROOT_PASSWORD=${DB_PASS}
      # - TZ=${TZ}


# ①定義宣言して名前でdb-storeこれでvolumeコンテナを作る。これは消さない限り消えない。
# 消したくない時に書く。

# ②ローカルのフォルダーと同期する。
#
volumes:
  db-store:
