version: “3.9”
services:
  kurumo_db:
    image: mysql:8.0
    container_name: kurumo_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --default-time-zone=SYSTEM
      --plugin-load-add=mysql_native_password.so
      --log-error=/var/log/mysql/mysql-error.log
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/mysql-slow.log
      --long-query-time=5.0
      --log-queries-not-using-indexes=0
      --general-log=1
      --general-log-file=/var/log/mysql/mysql-query.log
